name: my-ros-package
base: core20
version: '0.1.0'
summary: A sample ROS package with C++ publisher and subscriber nodes
description: |
  This snap includes a ROS package with sample C++ publisher and subscriber nodes,
  built using catkin and targeting ROS Noetic.

grade: stable
confinement: strict

parts:
  # base:
  #   plugin: nil
  #   stage-packages:
  #     - ros-noetic-ros-base
  #     - ros-noetic-std-msgs
  #     - ros-noetic-roscpp


  my-ros-package:
    # after:
    #   - base
    plugin: catkin
    source: src/
    source-type: local
    build-packages:
      - g++
      - cmake
      - build-essential
      # - catkin-tools
    stage-packages:
      - ros-noetic-ros-base
      - ros-noetic-std-msgs
      - ros-noetic-roscpp
    override-build: |
      # apt-get update
      apt-get install -y software-properties-common curl
      sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list'
      curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
      snapcraftctl build

apps:
  publisher:
    command: bin/publisher_node
    plugs:
      - network
      - network-bind

  subscriber:
    command: bin/subscriber_node
    plugs:
      - network

plugs:
  network:
    interface: network
  network-bind:
    interface: network-bind
