name: hello-world
base: core20
version: '0.1'
summary: A simple Hello World snap
description: |
  This is a minimal C++ Hello World snap using CMake.

grade: devel
confinement: strict

apps:
  hello-world:
    command: hello-world

parts:
  hello-world:
    plugin: dump
    source: ..
    source-type: local
    build-packages:
      - g++
      - cmake
    override-build:
      mkdir build && cd build &&
      cmake .. &&
      make &&
      cp hello-snap/ $SNAPCRAFT_PART_INSTALL/bin/
