name: hello-world
base: core20
version: '0.1'
summary: A simple Hello World snap
description: |
  This is a minimal C++ Hello World snap using CMake.

grade: devel
confinement: devmode

apps:
  hello-world:
    command: install/bin/hello-world

parts:
  hello-world:
    plugin: cmake
    source: .
    source-type: local
    organize:
      ./install/bin/*: install/bin/
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=install
    build-packages:
      - g++
      - cmake
    # override-build:
    #   mkdir build && cd build &&
    #   cmake .. &&
    #   make &&
    #   cp hello-snap/ $SNAPCRAFT_PART_INSTALL/bin/
