name: Snap_Build_Run_Main
on:
  workflow_dispatch:

  push:
    branches: ["main"]

jobs:

  build_snap:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v3

      - name: Build Snap
        run: |
          export SNAPCRAFT_BUILD_ENVIRONMENT=lxd
          snapcraft clean
          snapcraft
          ls
        shell: bash
        working-directory: ros-listener-talker/snap

  deploy:

    needs: build_snap
    runs-on: self-hosted
    steps: 
      - name: Install the snap
        run: |
          echo "${{ secrets.APP_PW }}" | sudo -S snap install --devmode ros-talker-listener*.snap 2>/dev/null || echo "Snap is installed"
          # isSnapPresent=$(snap list | awk '{print $1}' | grep "app")
          # if [ "$isSnapPresent" = "ros-talker-listener" ];
          # then
          #   echo "All good"
          # else
          #   echo "Snap not installed"
          #   exit 1
          # fi
        shell: bash
        working-directory: ros-listener-talker/snap

      - name: Run the snap app
        run: |
          screen -h 1000 -dmSL roslistener ros-talker-listener
          sleep 5
        shell: bash
        working-directory: ros-listener-talker/snap

      - name: Kill the app run
        run: |
          killall screen
        shell: bash
        working-directory: ros-listener-talker/snap

      - name: Verification
        run: |
          cat screenlog.0
        shell: bash
        working-directory: ros-listener-talker/snap

      - name: Clear the output file
        run: |
          rm screenlog.0
          rm *.snap
          echo "${{ secrets.APP_PW }}" | sudo -S snap remove ros-talker-listener*.snap
        shell: bash
        working-directory: ros-listener-talker/snap
